Match-Box-Team/FrontEnd

- .eslintrc.js
- .prettierrc
- package-lock.json
- package.json
- src/App.tsx
- src/index.tsx
<br/>
Prettier와 린트 설정
Airbnb 기반 린트 설정을 했고 프리티어도 몇몇 규칙을 추가했습니다
린트에는 주석을 달아놨고 Prettier에 대한 건 밑에 댓글을 보시면 됩니다
<br/>
프론트에서 사용할 Prettier와 린트 설정했습니다
<br/>
npm run start로 실행을 해봤습니다
<br/>
<br/>
> feat: Prettier, Lint 설정

- src/components/commons/layout/MainGrind.tsx
- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/chat/channel-page/sub-components/PwdSetModal.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
<br/>
무엇을 합니다!
- 일부 수정
- 
<br/>
- 비밀번호 입력 모달 추가
- 채널 입장 후 내 채널 목록에 추가 및 채널id 리코일로 넘겨주기 등
<br/>
closes: #30 Issue Number
- db 조작 후 프론트엔드에서 테스트
<br/>
<br/>
> Bug/30 공개 채널 페이지

- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
<br/>
무엇을 합니다!
- 게임 준비 페이지 틀
<br/>
- 게임 준비 페이지 틀을 만듦
<br/>
closes: #29 Issue Number
<br/>
<br/>
> feat:게임레디 틀

- package-lock.json
- package.json
- src/api/ChatRoomInfo.ts
- src/api/ProfileImge.ts
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
- src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
- src/components/pages/login/auth-page/Auth.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
- src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
<br/>
리코일에서 토큰을 가져오는 코드로 전환
<br/>
- 리코일에서 토큰을 가져오는 코드로 전환
<br/>
closes: #8 
<br/>
<br/>
> refactor: 리코일에서 토큰을 가져오는 코드로 전환

- package-lock.json
- package.json
- src/components/pages/login/auth-page/Auth.tsx
- src/recoil/locals/login/atoms/atom.tsx
<br/>
유저 정보에 recoil persist 적용
<br/>
- 새로고침 해도 유저 정보 초기화되지 않도록 수정
<br/>
closes: #8
<br/>
<br/>
> refactor: 유저 정보에 recoil persist 적용

- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/chatroom-page/components/InputChat.tsx
- src/components/pages/chat/chatroom-page/components/Message.tsx
- src/components/pages/chat/chatroom-page/hooks/index.tsx
<br/>
채팅방 채팅에 대해서 이미지 첨부하게 변경
훅 폴더를 만들어서 코드 중복 훅으로 뺌
<br/>
디자인 따라서 가기 위해서
<br/>
리액트 실행해봄
<br/>
<br/>
> feat: 채팅방 채팅에 대해서 이미지 첨부하게 변경

- src/components/commons/layout/MainGrind.tsx
- src/components/pages/chat/chatroom-page/components/InputChat.tsx
- src/components/pages/chat/chatroom-page/components/MessageList.tsx
- src/index.tsx
<br/>
채팅방페이지: 하단 채팅 입력창이 Layout 범위를 넘는 것 수정
프로젝트 전체: 최상위 폴더에 rem 설정
<br/>
위와 동일
<br/>
리액트를 실행해봄
<br/>
<br/>
> Featue/6 채팅방페이지: 하단 채팅 입력창 css 수정 / 프로젝트 전체: 최상위 폴더에 rem 설정

- src/api/BuyGame.ts
- src/api/GetGames.ts
- src/components/pages/game/game-modal/buygame-modal/BuyGame.tsx
- src/components/pages/game/gameshop-page/GameShop.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
- src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
<br/>
게임 구매 페이지, 마이 페이지  css 수정
<br/>
높이를 신경 쓰지 않았었음
<br/>
높이에 맞게 적당하게 화면이 잘 나오는 것 같음
<br/>
<br/>
> Refactor/49 refactor css 리팩토링

- src/Router.tsx
- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/playgame-page/PlayGame.tsx
- src/components/pages/game/playgame-page/game-socket/GameSocketContext.tsx
- src/components/pages/game/playgame-page/game-socket/GameSocketProvider.tsx
- src/components/pages/game/playgame-page/games/PingPong.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
무엇을 합니다!
- 핑퐁 게임과 관련, 백엔드에서 공과 패들 좌표를 받아 렌더링
<br/>
- 게임 플레이 기능
<br/>
- 게임 플레이 테스트
<br/>
<br/>
> Feature/22 게임 소켓 플레이

- src/components/pages/game/playgame-page/games/PingPong.tsx
<br/>
- 핑퐁 게임 렌더링 버그 고침
<br/>
- 핑퐁 게임 렌더링 버그
<br/>
closes: #63 
- 게임 테스트
<br/>
<br/>
> bug: 핑퐁 게임 렌더링 픽스

- src/components/pages/friend/bannedlist-page/BannedList.tsx
<br/>
친구 차단 목록에 친구 상태 표시 추가
<br/>
- 
<br/>
closes: #66 
- 
<br/>
<br/>
> refactor: 친구 상태 추가

- src/components/commons/modals/popup-modal/Popup.tsx
- src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
- src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
- src/components/pages/game/game-modal/buygame-modal/BuyGame.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/login/login-page/Login.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
- 특정 유저에게 게임 초대를 했을 시 초대 받은 유저의 화면에 게임 수락 모달이 뜸
- 게임 초대 보낸 유저 화면에 수락 대기 모달이 뜸
- 자기 자신, 로그인 안된 유저, 게임을 구매하지 않은 유저인 경우의 에러 처리
- 게임 중, 게임 준비 중인 유저인 경우 에러 처리
<br/>
- 가짜 유저 로그인 추가함
<br/>
- 게임 초대, 초대 수락, 거절, 취소 잘 동작함
- 에러 처리 잘 된 것 같음
<br/>
<br/>
> Feature/65 feature 게임 초대 수락 모달과 게임 초대 기능 구현

- src/Router.tsx
- src/components/pages/friend/addfriend-modal/AddFriend.tsx
- src/components/pages/friend/addfriend-page/AddFriend.tsx
- src/components/pages/friend/bannedlist-page/BannedList.tsx
- src/components/pages/friend/friendlist-page/FriendList.tsx
- src/components/pages/friend/friendlist-page/components/AddFriends.tsx
<br/>
친구 페이지 친구 추가
<br/>
- 친구 페이지 친구 추가
<br/>
closes: #59 
- 
<br/>
<br/>
> Feature/59 feature 친구 페이지 친구 추가

- src/api/Friends.ts
- src/components/commons/modals/profile-modal/Profile.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/friend/addfriend-modal/AddFriend.tsx
- src/components/pages/friend/friendlist-page/components/FriendDetailList.tsx
- src/components/pages/friend/friendlist-page/components/FrinedDetail.tsx
- src/components/pages/friend/friendlist-page/components/MyProfile.tsx
- src/components/pages/friend/friendlist-page/index.tsx
<br/>
친구 이미지 클릭 시 모달 구현
친구 밴 했을 시 자동으로 리스트 업데이트
친구 추가 시 다시 서버에 요청해서 친구목록 리스트 업데이트
자기 자신을 클릭했을 때 친구 목록 페이지로 이동하게 수정
<br/>
디자인 요구사항 충족
<br/>
closes: #54 
직접 리액트 프로젝트를 실행해서 테스트
<br/>
연관된 api에서 리액트 쿼리를 이용해서 서버에 POST를 보내면 GET으로 변경하게 수정
<br/>
> Feature/54 친구목록 페이지 만들기: 모달 및 모달에서 친구 추가, 밴을 할 시 친구목록 업데이트

- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/friend/addfriend-modal/AddFriend.tsx
- src/components/pages/friend/friendlist-page/components/AddFriends.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
<br/>
친구 상세 프로필 구현
<br/>
-
<br/>
closes: #75 
<br/>
<br/>
> feat: 친구 상세 프로필

- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/chatroom-page/index.tsx
<br/>
친구 프로필 dm 채팅
<br/>
- 친구 프로필 dm 채팅
<br/>
closes: #70 
- 
<br/>
<br/>
> feat: 친구 프로필 dm 채팅

- src/Router.tsx
- src/api/GameWatch.ts
- src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
- src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
- src/components/pages/game/game-modal/readygame-modal/Checkbox.tsx
- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/ready-game-page/ReadyGamePage.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/login/login-page/LoginSocketContext.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
게임 초대에서 게임 준비로 이어지는 로직들 구현
- 게임 초대 -> 수락, 거절, 취소
- 게임 준비 -> 방장만 속도 선택, 게임 시작 가능, 취소
<br/>
<br/>
- 자잘한 버그들이 아직 있는 것 같긴 합니다...
예외 처리)
- 초대한 유저가 게임이 없을 때
- 로그인하지 않은 유저가 있을 때
- 이미 게임 중인 유저일 때
- 초대 수락했는데 초대 보낸 사람이 취소했을 때 등등
<br/>
<br/>
> Feature/69 feature 게임 준비 방 생성

- src/components/pages/game/playgame-page/PlayGame.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
<br/>
무엇을 합니다!
- 게임 승패 정해진 후 모달
<br/>
- 게임 승패 알림 모달
<br/>
<br/>
<br/>
> Featrue/77 게임 승패 기록

- src/Router.tsx
- src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
- src/components/pages/game/game-modal/matching-modal/Matching.tsx
- src/components/pages/game/gameshop-page/GameShop.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
- 마이 페이지 게임 선택 상태 관리 코드 수정
- 잔버그 수정(플레이 못하는 게임인데 구매 가능, 공개/비공개 -> 비공개/공개)
<br/>
<br/>
<br/>
<br/>
> Refactor/84 refactor 마이 페이지 게임 선택 상태 관리 코드 수정

- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/playgame-page/games/PingPong.tsx
<br/>
- 게임 후 게임 결과 저장
- host/guest 소켓 구분 
<br/>
- 게임 플레이 결과 저장
<br/>
closes: #82 Issue Number
<br/>
<br/>
> Feature/82 매칭유저 게임 연결

- src/components/commons/modals/profile-modal/Profile.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/login/login-page/Login.tsx
<br/>
채팅방 내에서 프로필 눌렀을 때만 isadmin api 요청 사용
<br/>
- 친구 목록에서 프로필 눌렀을 때 불필요하게 isAdmin api 요청
<br/>
closes: #91
<br/>
<br/>
> Bug/91 bug 채팅방 내에서 프로필 눌렀을 때만 isadmin api 요청 사용

- src/Router.tsx
- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
<br/>
- 게임워치id 별 게임 관리를 위한 프론트 엔드 코드 수정
<br/>
- 이러한 이유 때문에 변경했습니다!
<br/>
closes: #93 Issue Number
- 게임 플레이 해봄
<br/>
<br/>
> feat: 룸별로 게임

- src/components/commons/modals/profile-modal/Profile.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
<br/>
채팅방에서 리코일 대신 url 경로의 채널 아이디 사용
<br/>
- 채팅방에서 새로고침하면 리코일의 채널 아이디가 초기화되는 상황 해결
<br/>
closes: #94 
- 
<br/>
<br/>
> refactor: 채팅방에서 리코일 대신 url 경로의 채널 아이디 사용

- src/components/commons/footer/Footer.tsx
- src/components/commons/modals/profile-modal/Profile.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/channel-page/Channel.tsx
- src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/mymsg-page/MyMsg.tsx
- src/components/pages/friend/bannedlist-page/BannedList.tsx
- src/components/pages/friend/friendlist-page/FriendList.tsx
- src/recoil/locals/footer/atoms/footerAtom.tsx
<br/>
채널 목록과 친구 목록 이전 페이지 기억
<br/>
- 채널 목록과 친구 목록 이전 페이지 기억
<br/>
closes: #24 
- 
<br/>
<br/>
> Feature/24 refactor 채널 목록과 친구 목록 이전 페이지 기억

- src/api/Channel.ts
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/chatroom-page/index.tsx
<br/>
ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는 문제 해결
<br/>
- ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는 문제
<br/>
closes: #98 
<br/>
<br/>
> ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는 문제

- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/playgame-page/PlayGame.tsx
- src/components/pages/game/playgame-page/games/PingPong.tsx
<br/>
다중 게임 실시간 렌더링 안됨 버그
<br/>
다중 게임 실시간 렌더링 안됨 버그
ready emit 이벤트 중복 수정
<br/>
유저 4명 각자 둘둘 게임 할 떄 않 끊기고 잘 병렬로 돌아가는 것 같음
<br/>
<br/>
> Bug/102 bug 다중 게임 실시간 렌더링 안됨 버그

- src/api/Channel.ts
- src/components/commons/error/ErrorPopupNav.tsx
- src/components/pages/login/auth-page/Auth.tsx
- src/components/pages/login/login-page/Login.tsx
<br/>
refactor 코드 인증 유저 정보 쿠키 대신 state로 관리
<br/>
- 새로고침 했을 때 타이머 초기화되는 문제 해결
<br/>
closes: #104 
- 
<br/>
<br/>
> Refactor/104 refactor 코드 인증 유저 정보 쿠키 대신 state로 관리

- src/api/Channel.ts
- src/components/commons/error/ErrorPopup.tsx
- src/components/commons/error/ErrorPopupNav.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/login/auth-page/Auth.tsx
- src/components/pages/login/login-page/Login.tsx
<br/>
채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력
<br/>
- 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력
<br/>
closes: #109
<br/>
<br/>
> Refactor/109 refactor 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력

- src/components/commons/error/ErrorPopup.tsx
- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/game/game-modal/matching-modal/Matching.tsx
- src/components/pages/game/playgame-page/PlayGame.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
- 매칭 취소 게임 중 나감 등등 처리
- error popup 모달 수정
<br/>
- error popup 모달: 밖을 누르면 꺼지게 수정
<br/>
- 랜덤 매칭 취소
- 게임 중 GG, 나감 처리
<br/>
<br/>
> Feature/108 feature 매칭 취소 게임 중 나감 등등 처리

- src/components/commons/error/ErrorPopup.tsx
<br/>
merge 실수 중복 코드 제거
<br/>
ModalOutside 중복 선언
<br/>
<br/>
<br/>
> fix/108 fix Merge 실수 수정

- src/components/commons/error/ErrorPopupNav.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/friend/addfriend-modal/AddFriend.tsx
- src/components/pages/friend/bannedlist-page/BannedList.tsx
- src/components/pages/login/auth-page/Auth.tsx
- src/components/pages/login/login-page/Login.tsx
<br/>
friends 기능 에러 모달 사용
<br/>
- friends 기능 에러 모달 사용
<br/>
closes: #115 
- 
<br/>
<br/>
> refactor: friends 기능 에러 모달 사용

- src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
- src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
<br/>
channels 기능 에러 모달 사용
<br/>
- channels 기능 에러 모달 사용
<br/>
closes: #117 
<br/>
<br/>
> Refactor/117 refactor channels 기능 에러 모달 사용

- src/components/commons/error/ErrorPopupNav.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
<br/>
- 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결
<br/>
- 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결
<br/>
closes: #119 
<br/>
<br/>
> bug: 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결

- src/components/commons/error/ErrorPopupNav.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
- src/components/pages/game/gameshop-page/GameShop.tsx
- src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
<br/>
게임 샵 에러 해결
<br/>
- 게임 샵 에러 해결
<br/>
closes: #121 
<br/>
<br/>
> Bug/121 bug 게임 샵 에러 해결

- src/api/Channel.ts
- src/components/commons/error/ErrorPopupNav.tsx
- src/components/commons/modals/profile-modal/Profile.tsx
- src/components/commons/modals/profile-modal/ProfileFooter.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/chatroom-page/index.tsx
<br/>
킥 소켓 사용
<br/>
- 킥 소켓 사용
<br/>
closes: #124 
<br/>
<br/>
> bug: 킥 소켓 사용

- src/api/AddFriend.ts
- src/api/BuyGame.ts
- src/api/ChatRoomInfo.ts
- src/api/GameWatch.ts
- src/api/GetGames.ts
- src/api/InviteChatRoom.ts
- src/api/ProfileImge.ts
- src/api/SetAdmin.ts
- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/chat/chat-modal/createroom-modal/Createroom.tsx
- src/components/pages/chat/chat-modal/invite-modal/Invite.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/chat/chat-modal/setroom-modal/SetRoom.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/login/login-page/Login.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
- src/components/pages/profiles/profile-modal/editmy-modal/EditMy.tsx
<br/>
백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정
<br/>
백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정
<br/>
<br/>
<br/>
> Refactor/128 refactor 백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정

- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
<br/>
채널 리스트 페이지 새로고침 이슈 해결
<br/>
- 채널 리스트 페이지 새로고침 이슈 해결
<br/>
closes: #81 
<br/>
<br/>
> bug: 채널 리스트 페이지 새로고침 이슈 해결

- src/components/pages/game/game-modal/accept-game-modal/AcceptModal.tsx
- src/components/pages/game/game-modal/accept-waiting-modal/AcceptWaiting.tsx
- src/components/pages/game/game-modal/matching-modal/Matching.tsx
- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/playgame-page/games/PingPong.tsx
- src/components/pages/game/watchgame-page/GamePage.tsx
- src/components/pages/login/login-page/CheckLogin.tsx
- src/components/pages/login/login-page/Login.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
<br/>
- 이메일 양식 수정 및 console.log 제거
<br/>
- 이메일 양식 수정 및 console.log 제거
<br/>
<br/>
<br/>
> refactor: 이메일 양식 수정 및 console.log 제거

- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/chatroom-page/index.tsx
<br/>
채팅 소켓 에러 메시지 분리
<br/>
- 채팅 소켓 에러 메시지 분리
<br/>
closes: #138 
<br/>
<br/>
> refactor: 채팅 소켓 에러 메시지 분리

- src/components/pages/friend/friendlist-page/components/MyProfile.tsx
- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/ready-game-page/ReadyGamePage.tsx
<br/>
게임 준비 취소
<br/>
게임 준비 취소
<br/>
<br/>
<br/>
> Bug/140 bug 게임 준비 취소

- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
<br/>
- gameStartError socker.off 추가
<br/>
- gameStartError socker.off 추가
<br/>
<br/>
<br/>
> fix: gameStartError socker.off 추가

- src/components/pages/game/watchgame-page/GamePage.tsx
- src/components/pages/game/watchgame-page/component/ErrorGame.tsx
<br/>
게임 히스토리에 URL 404 처리해서 404로 이동하게 설정
에러 모달 클릭 시 리다이렉션
게임 히스토리는 마이 페이지이나 친구 페이지
게임 와치는 게임 샵으로
<br/>
배포 전 버그 발견
<br/>
closes: #143 
직접 로컬 프론트와 로컬 백엔드에서 테스트
<br/>
<br/>
> Feature/143 게임 히스토리에 url 404 처리와 에러 모달 클릭 시 리다이렉션

- src/components/pages/game/watchgame-page/GamePage.tsx
<br/>
게임 페이지 consoleerror error 모달 수정
<br/>
- 게임 페이지 consoleerror error 모달 수정
<br/>
closes: #145 
<br/>
<br/>
> Refactor/145 refactor 게임 페이지 consoleerror error 모달 수정

- src/api/Channel.ts
- src/components/pages/chat/channel-page/sub-components/ChannelList.tsx
- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/profiles/friend-page/FriendProfile.tsx
- src/components/pages/profiles/my-page/MyProfile.tsx
<br/>
채널 API에서 리스트 여러 번 요청하는 것에 리액트 쿼리로 변경
await 안 달려 있는 부분에 await 달기
<br/>
배포 전 버그 발생
<br/>
closes: #147 
직접 실행해서 테스트
<br/>
<br/>
> Feature/147 channel 리스트 페이지에 채널 목록 여러 개 요청하는 부분 수정

- src/components/pages/chat/chat-modal/roomside-modal/RoomSide.tsx
- src/components/pages/login/login-page/Login.tsx
while HOTFIX!
main branch aheat to develop
> Merege To develop to main for Sync with branch

- src/components/pages/game/game-modal/readygame-modal/ReadyGame.tsx
- src/components/pages/game/playgame-page/PlayGame.tsx
- src/components/pages/game/ready-game-page/ReadyGamePage.tsx
<br/>
gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정
<br/>
- gamewatchid가 없는데도 들어가져서 게임 초기 화면이 나왔었음
- any타입 수정
<br/>
<br/>
<br/>
> Refactor/157 refactor gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정

- src/components/pages/game/playgame-page/games/PingPong.tsx
<br/>
무엇을 합니다!
- any 타입을 특정 타입으로 대체
<br/>
- 타입스크립트 스러운 개발 리팩토링
<br/>
closes: #156 Issue Number
- 리팩토링 이전과 같은 동작 확인 테스트
<br/>
<br/>
> Refactor/156 pinpong any 타입 제거

- src/api/Channel.ts
- src/components/commons/header/Header.tsx
- src/components/pages/chat/chatroom-page/ChatRoomt.tsx
- src/components/pages/chat/mymsg-page/sub-components/MyMsgList.tsx
<br/>
내가 속한 채널 목록 페이지 불필요한 랜더링 이슈 해결
<br/>
- 내가 속한 채널 목록 페이지 불필요한 랜더링 이슈 해결
<br/>
closes: #161 
<br/>
<br/>
> Bug/161 bug 내가 속한 채널 목록 페이지 불필요한 랜더링 이슈
